import _SachsenIcon from './icons/sachsen.svg?component';
import _AdminIcon from './icons/admin.svg?component';
import _HumanIcon from './icons/human.svg?component';
import _CrossIcon from './icons/cross.svg?component';
import _UnderlineIcon from './icons/underline.svg?component';
import _DefaultCurosrIcon from './icons/cursor_default.svg?component';
import _PointerCurosrIcon from './icons/cursor_pointer.svg?component';
import _UnpointerCurosrIcon from './icons/cursor_unpointer.svg?component';
import _MoveCurosrIcon from './icons/cursor_move.svg?component';
import _FolderIcon from './icons/folder.svg?component';
import _TrashcanIcon from './icons/trashcan.svg?component';
import _ExitIcon from './icons/exit.svg?component';

export const SachsenIcon = _SachsenIcon;
export const AdminIcon = _AdminIcon;
export const HumanIcon = _HumanIcon;
export const CrossIcon = _CrossIcon;
export const UnderlineIcon = _UnderlineIcon;
export const DefaultCurosrIcon = _DefaultCurosrIcon;
export const PointerCurosrIcon = _PointerCurosrIcon;
export const UnpointerCurosrIcon = _PointerCurosrIcon;
export const MoveCurosrIcon = _PointerCurosrIcon;
export const FolderIcon = _FolderIcon;
export const TrashcanIcon = _TrashcanIcon;
export const ExitIcon = _ExitIcon;